#
# 
#

##################################################
# LoRa detection library
##################################################
LORA_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/custom/, \
./lora_detect.vhd \
./dsp_add48_48.vhd \
./dsp_mult18_48.vhd \
./complex_module.vhd \
))
