#
# Copyright 2014 Ettus Research LLC
#

##################################################
# radio library
##################################################
LORA_DETECT_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/lora_detect/, \
./lora_detect.v \
))
